config/routes.rb
Rails.application.routes.draw do
  resources :banner_items
  resources :likes
  resources :inventories
  resources :transanctions
  resources :codes
  resources :items
  resources :banners
  resources :users
  
  get '/main' ,to: 'user#login'
  get '/out' ,to: 'user#pre_login'
  get '/logout' ,to: 'user#logout'
  get '/new_user', to: 'user#new_user'
  get '/gacha' ,to: 'user#gacha'
  get '/like/:id' ,to: 'user#like' 
  get '/unlike/:id' ,to: 'user#unlike' 
  get '/error' ,to: 'user#error'
  get '/market' ,to: 'user#market'
  
  
  get '/inventory' ,to: 'inventories#inventory'
  get '/banner/:name', to: 'banners#banner_gacha'
  
  
  get '/redeem', to: 'codes#redeem'
  
  post '/user/new', to: 'user#new'
  post '/new_user', to: 'user#new_user'
  post '/create_user', to: 'user#create_user'
  post '/cancel/:name', to: 'user#cancel'
  
  post '/banner/:name/pull_one', to: 'banners#pull_one'
  post '/banner/:name/pull_ten', to: 'banners#pull_ten'
  post '/how_to_obtain/:name', to: 'banners#how_to_obtain'
  
  
  post '/redeem/code', to: 'codes#redeem_code'
  
  patch '/sell/:name', to: 'user#sell'
  patch '/buy/:name', to: 'user#buy'
  
  post '/login_attempt', to: 'user#login_attempt'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/banner.rb
class Banner < ApplicationRecord
   
   has_many :likes
   has_many :banner_items
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: %i[ show edit update destroy ]

  before_action :logged_in, only: %i[ banner_gacha pull_one pull_ten how_to_obtain ]
  
  # GET /banners or /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1 or /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners or /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: "Banner was successfully created." }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1 or /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to @banner, notice: "Banner was successfully updated." }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1 or /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: "Banner was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def banner_gacha
    @banner = Banner.find_by(name: params[:name])
    if(@banner)
    else
      redirect_to "/error"
      return
    end
    puts @banner
    @rate = Array.new
    @all_rate = 0
    @banner.banner_items.each do |item|
      @rate.push([item.rate.to_i,item.item])
      @all_rate += item.rate.to_i
    end
  end
  def pull_one
    @banner = Banner.find_by(name: params[:name])
    @all_items = @banner.banner_items
    @roll = Array.new
    @all_items.each do |item|
      @roll+= [item.item]*item.rate.to_i
      puts @roll.size
    end
    
    #Calculate the price
    @user = User.find(session[:user_id])
    if(@user.credit.to_i < @banner.price.to_i)
      redirect_to "/banner/#{params[:name]}", notice: "You don't have enough credit"
      return
    else
      @user.credit -= @banner.price
    end
    
    #random something out once
    #Add them to user inventory
    @got_items = Array.new
    for i in 1..1 do
      @roll = @roll.shuffle
      @item = @roll.sample
      @got_items.push(@item)
      @inventory = Inventory.find_by(user_id: session[:user_id], item_id: @item.id)
      if(@inventory)
        @inventory.amount+=1
        @inventory.save
      else
        @inventory = Inventory.new(user_id: session[:user_id], item_id: @item.id,amount: 1)
        @inventory.save
      end
    end
    @user.save
    
  end
  
  def pull_ten
    @banner = Banner.find_by(name: params[:name])
    @all_items = @banner.banner_items
    @roll = Array.new
    @all_items.each do |item|
      @roll+= [item.item]*item.rate.to_i
      puts @roll.size
    end
    
    #Calculate the price
    @user = User.find(session[:user_id])
    if(@user.credit < @banner.price*10)
      redirect_to "/banner/#{params[:name]}", notice: "You don't have enough credit"
      return
    else
      @user.credit -= @banner.price*10
    end
    
    #random something out once
    #Add them to user inventory
    @got_items = Array.new
    @each_items = Hash.new
    for i in 1..10 do
      @roll = @roll.shuffle
      @item = @roll.sample
      @got_items.push(@item)
      if(@each_items[@item])
        @each_items[@item] += 1
      else
        @each_items[@item] = 1
      end
      @inventory = Inventory.find_by(user_id: session[:user_id], item_id: @item.id)
      if(@inventory)
        @inventory.amount+=1
        @inventory.save
      else
        @inventory = Inventory.new(user_id: session[:user_id], item_id: @item.id,amount: 1)
        @inventory.save
      end
    end
    
    
    
    @user.save
    
    #generate Modal
    @attr = @got_items.join('').html_safe
    #redirect_to "/banner/#{params[:name]}", :flash => { :items => @got_items }
  end
  
  
  def how_to_obtain
    @item = Item.find_by(name: params[:name],onsale: "no")
    @banner_item = BannerItem.where(item_id: @item.id)
    @banners = Array.new
    @banner_item.each do |banner|
      @banners.push(banner.banner)
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def logged_in
      if(session[:user_id])
        a = 1
      else
        session[:user_id] = nil
        redirect_to "/main", notice: "Please login"
        return
      end
    end
    
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banner_params
      params.require(:banner).permit(:name, :startDate, :endDate, :price)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= form_with(model: banner) do |form| %>
  <% if banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
        <% banner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :startDate %>
    <%= form.date_select :startDate %>
  </div>

  <div class="field">
    <%= form.label :endDate %>
    <%= form.date_select :endDate %>
  </div>
  
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/banners/banner_gacha.haml
%p#notice= notice
%div
  %p
    %strong Bannername:
    = @banner.name
  
  %p
    %strong startdate:
    = @banner.startDate
  %p
    %strong enddate:
    = @banner.endDate
%div
  = button_to "pull 1 for #{@banner.price}", "/banner/#{@banner.name}/pull_one"
  = button_to "pull 10 for #{@banner.price*10}", "/banner/#{@banner.name}/pull_ten" 
Rate
%table
  %thead
    %tr
      %th Item img
      %th Itemname
      %th Rarity
      %th rate
      %th{:colspan => "3"}
  %tbody
    - @rate.each do |item|
      %tr
        %td 
          %img{:src => item[1].item_img_url, :width => "200", :height => "auto"}
        %td= item[1].name
        %td= item[1].rarity
        %td= item[0].to_f/@all_rate 

.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :id => "exampleModal", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Like People
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
      .modal-body
      .modal-footer
        %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Close
        
:javascript
  console.log("hello")
  $(".button_to").click(function(){
    var Modal = $('.modal');
    var Modaltext = $('.modal-body');
    Modaltext.toggle;
    Modaltext.html(@got_items.join('<br>'));
  })
  
:javascript
  console.log("hello")
  $(".show").click(function(){
    var post = $(this).prev();
    var numlike = post.html();
    var Modal = $('.modal');
    var Modaltext = $('.modal-body');
    console.log(numlike);
    console.log($(this).attr("attr"));
    Modaltext.html(numlike);
    Modaltext.html(numlike + "<br>" +$(this).attr("attr"));
    
  })

app/views/banners/edit.html.erb
<h1>Editing Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/how_to_obtain.haml
%p#notice= notice
%h1 How to obtain #{@item.name}
%table
  %thead
    %tr
      %th Bannername
      %th Bannerstartdate
      %th Bannerenddate
      %th{:colspan => "3"}
  %tbody
    - @banners.each do |banner|
      %tr
        %td= banner.name
        %td= banner.startDate
        %td= banner.endDate
        %td= link_to 'Go to gacha', "/banner/#{banner.name}"
%br

app/views/banners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Banners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.name %></td>
        <td><%= banner.startDate %></td>
        <td><%= banner.endDate %></td>
        <td><%= banner.price %></td>
        <td><%= link_to 'Show', banner %></td>
        <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
        <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New Banner</h1>

<%= render 'form', banner: @banner %>

<%= link_to 'Back', banners_path %>

app/views/banners/pull_one.haml
%p#notice= notice
%h1 You got ...
%table
  %thead
    %tr
      %th Item img
      %th Itemname
      %th Rarity
      %th Amount
      %th{:colspan => "3"}
  %tbody
    - @got_items.each do |item|
      %tr
        %td 
          %img{:src => item.item_img_url, :width => "200", :height => "auto"}
        %td= item.name
        %td= item.rarity
        %td "1"

app/views/banners/pull_ten.haml
%p#notice= notice
%h1 You got ...
%table
  %thead
    %tr
      %th Item img
      %th Itemname
      %th Rarity
      %th Amount
      %th{:colspan => "3"}
  %tbody
    - @each_items.each do |key,value|
      %tr
        %td 
          %img{:src => key.item_img_url, :width => "200", :height => "auto"}
        %td= key.name
        %td= key.rarity
        %td= value 

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>BannerName:</strong>
  <%= @banner.name %>
</p>

<p>
  <strong>Bannerstartdate:</strong>
  <%= @banner.startDate %>
</p>

<p>
  <strong>Bannerenddate:</strong>
  <%= @banner.endDate %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>