config/routes.rb
Rails.application.routes.draw do
  resources :banner_items
  resources :likes
  resources :inventories
  resources :transanctions
  resources :codes
  resources :items
  resources :banners
  resources :users
  
  get '/main' ,to: 'user#login'
  get '/out' ,to: 'user#pre_login'
  get '/logout' ,to: 'user#logout'
  get '/new_user', to: 'user#new_user'
  get '/gacha' ,to: 'user#gacha'
  get '/like/:id' ,to: 'user#like' 
  get '/unlike/:id' ,to: 'user#unlike' 
  get '/error' ,to: 'user#error'
  get '/market' ,to: 'user#market'
  
  
  get '/inventory' ,to: 'inventories#inventory'
  get '/banner/:name', to: 'banners#banner_gacha'
  
  
  get '/redeem', to: 'codes#redeem'
  
  post '/user/new', to: 'user#new'
  post '/new_user', to: 'user#new_user'
  post '/create_user', to: 'user#create_user'
  post '/cancel/:name', to: 'user#cancel'
  
  post '/banner/:name/pull_one', to: 'banners#pull_one'
  post '/banner/:name/pull_ten', to: 'banners#pull_ten'
  post '/how_to_obtain/:name', to: 'banners#how_to_obtain'
  
  
  post '/redeem/code', to: 'codes#redeem_code'
  
  patch '/sell/:name', to: 'user#sell'
  patch '/buy/:name', to: 'user#buy'
  
  post '/login_attempt', to: 'user#login_attempt'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/code.rb
class Code < ApplicationRecord
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: %i[ show edit update destroy ]
  
  
  before_action :logged_in, only: %i[ redeem redeem_code ]
  # GET /codes or /codes.json
  def index
    @codes = Code.all
  end

  # GET /codes/1 or /codes/1.json
  def show
  end

  # GET /codes/new
  def new
    @code = Code.new
  end

  # GET /codes/1/edit
  def edit
  end

  # POST /codes or /codes.json
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: "Code was successfully created." }
        format.json { render :show, status: :created, location: @code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codes/1 or /codes/1.json
  def update
    respond_to do |format|
      if @code.update(code_params)
        format.html { redirect_to @code, notice: "Code was successfully updated." }
        format.json { render :show, status: :ok, location: @code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1 or /codes/1.json
  def destroy
    @code.destroy
    respond_to do |format|
      format.html { redirect_to codes_url, notice: "Code was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def redeem
    #not here
    @code = Code.new
    if(flash[:error])
      @code.errors.add :code, :redeem_failed, message: "with Wrong Code or Expired or Already Redeemed"
    end
  end
  
  def redeem_code
    #not here
    @code = Code.find_by(code: params[:code][:code])
    
    if(!@code)
      
      @code = Code.new
      @code.errors.add :code, :redeem_failed, message: "with Wrong Code or Expired"
      redirect_to "/redeem", :flash => { :error => @code.errors }
      return
    end
    if(@code.status != "available")
      @code.errors.add :code, :redeem_failed, message: "with Wrong Code or Expired"
      redirect_to "/redeem", :flash => { :error => @code.errors }
      return
    end
    
    @user = User.find(session[:user_id])
    @user.credit += @code.creditAmount
    @code.status = "redeemed"
    @code.save
    @user.save
    redirect_to "/redeem", :notice => "Redeem Successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def logged_in
      if(session[:user_id])
        a = 1
      else
        session[:user_id] = nil
        redirect_to "/main", notice: "Please login"
        return
      end
    end
    
    def set_code
      @code = Code.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def code_params
      params.require(:code).permit(:creditAmount, :status, :code)
    end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<%= form_with(model: code) do |form| %>
  <% if code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
        <% code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :creditAmount %>
    <%= form.number_field :creditAmount %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>
  
  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing Code</h1>

<%= render 'form', code: @code %>

<%= link_to 'Show', @code %> |
<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Codes</h1>

<table>
  <thead>
    <tr>
      <th>Creditamount</th>
      <th>Status</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @codes.each do |code| %>
      <tr>
        <td><%= code.creditAmount %></td>
        <td><%= code.status %></td>
        <td><%= code.code %></td>
        <td><%= link_to 'Show', code %></td>
        <td><%= link_to 'Edit', edit_code_path(code) %></td>
        <td><%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Code', new_code_path %>

app/views/codes/inventory.haml
%p#notice= notice
%h1 Inventories
%table
  %thead
    %tr
      %th Item img
      %th Itemname
      %th Rarity
      %th Amount
      %th{:colspan => "3"}
  %tbody
    - @items.each_with_index do |item,index|
      %tr
        %td 
          %img{:src => item.item_img_url, :width => "200", :height => "auto"}
        %td= item.name
        %td= item.rarity
        %td= @number_items[index] 
        %td
          = form_with(model: item, url: "/sell/#{item.name}") do |form|
            
            .field
              = form.label :price
              = form.number_field :price
            .field
              = form.label :amount
              = form.number_field :amount
            .actions
              = form.submit "Sell", class: "btn btn-dark"
        %td= button_to 'How to obtain', "/how_to_obtain/#{item.name}"

%h1 onsale Inventories
%table
  %thead
    %tr
      %th Item img
      %th Itemname
      %th Rarity
      %th Amount
      %th Price
      %th{:colspan => "3"}
  %tbody
    - @sell_items.each_with_index do |item,index|
      %tr
        %td 
          %img{:src => item.item_img_url, :width => "200", :height => "auto"}
        %td= item.name
        %td= item.rarity
        %td= @number_sell_items[index][0] 
        %td= @number_sell_items[index][1] 
        %td= button_to 'Cancel', "/cancel/#{item.name}", class: "btn btn-dark"

app/views/codes/new.html.erb
<h1>New Code</h1>

<%= render 'form', code: @code %>

<%= link_to 'Back', codes_path %>

app/views/codes/redeem.haml
%p#notice= notice
= form_with(model: @code, url: "/redeem/code",label_errors: true, inline_errors: true) do |form|

  .field
    = form.label :code, class: "form-label form-control-label"
    = form.text_field :code, class: "is-invalid"
  .actions
    = form.submit "redeem", class: "btn btn-dark"

app/views/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creditamount:</strong>
  <%= @code.creditAmount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @code.status %>
</p>

<p>
  <strong>Code:</strong>
  <%= @code.code %>
</p>
<%= link_to 'Edit', edit_code_path(@code) %> |
<%= link_to 'Back', codes_path %>